import { useLocalSearchParams, useRouter } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { loadMyFinalPayslip, type PayslipDetail } from '@/src/features/payslips/payslip-api';
import { usePlatform } from '@/src/providers/platform-provider';
const won=(v:number|null)=>v==null?'-':`${new Intl.NumberFormat('ko-KR').format(v)}원`;
export default function PayslipDetailScreen(){const router=useRouter();const insets=useSafeAreaInsets();const {month}=useLocalSearchParams<{month?:string}>();const {client,session}=usePlatform();const [item,setItem]=useState<PayslipDetail|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const load=useCallback(async()=>{if(!client||!session||!month)return;setLoading(true);setError('');try{setItem(await loadMyFinalPayslip(client,month));}catch{setError('급여명세서를 불러오지 못했습니다. 다시 눌러주세요.');}finally{setLoading(false);}},[client,session,month]);useEffect(()=>{void load();},[load]);return <View style={[s.page,{paddingTop:insets.top,paddingBottom:insets.bottom}]}><ScrollView contentContainerStyle={s.scroll}><Pressable accessibilityRole="button" accessibilityLabel="급여명세 목록으로 돌아가기" onPress={()=>router.replace('/payslips')}><Text style={s.back}>← 급여명세</Text></Pressable>{loading?<View style={s.loading}><ActivityIndicator/><Text style={s.help}>명세서를 확인하고 있습니다.</Text></View>:null}{!loading&&error?<Pressable onPress={()=>void load()} style={s.retry}><Text style={s.retryText}>{error}</Text><Text style={s.retryText}>다시 확인</Text></Pressable>:null}{!loading&&!error&&item?<><Text style={s.title}>{item.payroll_month.slice(0,7)} 확정 급여명세</Text><View style={s.card}><Text style={s.key}>지급액 · {won(item.gross_pay)}</Text><Text style={s.key}>공제액 · {won(item.total_deduction)}</Text><Text style={s.net}>실수령액 · {won(item.net_pay)}</Text></View><View style={s.card}><Text style={s.section}>공제 항목</Text>{item.deductions.filter(x=>x.amount!=null).map(x=><Text key={x.label} style={s.line}>{x.label} · {won(x.amount)}</Text>)}</View><Text style={s.help}>이 화면은 확정된 서버 원장 결과를 표시하며 계산하거나 수정할 수 없습니다.</Text></>:null}</ScrollView></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#f6f4ed'},scroll:{gap:14,padding:22,paddingBottom:40},back:{color:'#35624d',fontSize:16,fontWeight:'800',minHeight:42},title:{color:'#173f31',fontSize:30,fontWeight:'900',lineHeight:39},loading:{flexDirection:'row',gap:10,alignItems:'center',paddingVertical:16},help:{color:'#60746a',fontSize:15,lineHeight:22},card:{gap:10,padding:18,borderRadius:18,borderWidth:1,borderColor:'#d7ded8',backgroundColor:'#fff'},key:{color:'#173f31',fontSize:18,fontWeight:'800'},net:{color:'#173f31',fontSize:21,fontWeight:'900'},section:{color:'#173f31',fontSize:18,fontWeight:'900'},line:{color:'#43584d',fontSize:16,fontWeight:'700'},retry:{gap:8,padding:16,borderRadius:16,backgroundColor:'#fff0ed'},retryText:{color:'#8b2f2f',fontSize:15,fontWeight:'800',textAlign:'center'}});
